### ISSUE TITLE
TypeError: invalid input argument. Must provide an error object

### ISSUE THREAD

**Issue by persedir** [kgryte/utils-copy-error#3]
**Code:**
```javascript
const clone= require('utils-copy-error');

const error= new Error('hello');

const cloned= clone(error);

console.log(error);
console.log(cloned);
```
**Output in terminal:**
```bash
TypeError: invalid input argument. Must provide an error object. Value: `Error: hello`.
    at copy (/home/runner/node_modules/utils-copy-error/lib/copy.js:26:9)
    at evalmachine.<anonymous>:5:15
    at Script.runInContext (vm.js:133:20)
    at Object.runInContext (vm.js:311:6)
    at evaluate (/run_dir/repl.js:133:14)
    at ReadStream.<anonymous> (/run_dir/repl.js:116:5)
    at ReadStream.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at ReadStream.Readable.push (_stream_readable.js:224:10)
```

**Comment by lamualfa** [comment]
I have done a pull request: #4

**Comment by kgryte** [comment]
Hmm...are you running this code in the REPL? If so, the `instanceof` check may fail due to an `Error` object originating from a different "realm".

**Comment by kgryte** [comment]
Instead of the `instanceof` brand check, may be better to use more robust checking [logic](https://github.com/stdlib-js/stdlib/blob/9512dbeb4fe905653383d2fd78f5fb5a3c6a91ca/lib/node_modules/%40stdlib/assert/is-error/lib/main.js).
