### ISSUE TITLE
Unable to Copy ERR_INVALID_ARG_TYPE Errors

### ISSUE THREAD

**Issue by thelaughingwolf** [kgryte/utils-copy-error#5]
#### Steps to reproduce 
1. Use `utils-copy-error` to copy a `TypeError [ERR_INVALID_ARG_TYPE]` error in Node
2. See new error thrown by Node

#### Current behaviour
Copying a `TypeError [ERR_INVALID_ARG_TYPE]` error results in Node throwing a _new_ `TypeError [ERR_INVALID_ARG_TYPE]` error instead of providing the error being copied.

#### Expected behaviour
The original error is returned as-is.

##### Original error (from `console.error`):
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
```

##### Error produced by module:
```
AssertionError [ERR_ASSERTION]: Code: ERR_INVALID_ARG_TYPE; The provided arguments length (1) does not match the required ones (3).
    at getMessage (internal/errors.js:220:5)
    at new NodeError (internal/errors.js:159:13)
    at copy (/opt/ws/webapps/apiv3/node_modules/utils-copy-error/lib/copy.js:29:8)
```

#### Other comment
I ran into this when trying to copy an error produced by `Path.join` with an undefined entry.

**Comment by kgryte** [comment]
@thelaughingwolf Thanks for reporting this issue. Would you be able to provide a minimal code snippet I can use to reproduce this issue? Thanks!

**Comment by thelaughingwolf** [comment]
Absolutely!

```
const Path = require('path');
const copy = require('utils-copy-error');
let error
,	copiedError;

try {
	Path.join(undefined, undefined);
} catch (e) {
	error = e;
}

console.error(`Original error:`, error);
/*
Prints:
	Original error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
		at validateString (internal/validators.js:121:11)
		at Object.join (path.js:375:7)
		at Object.<anonymous> (example.js:6:7)
		at Module._compile (internal/modules/cjs/loader.js:1256:30)
		at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
		at Module.load (internal/modules/cjs/loader.js:1105:32)
		at Function.Module._load (internal/modules/cjs/loader.js:967:14)
		at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
		at internal/main/run_main_module.js:17:47 {
		code: 'ERR_INVALID_ARG_TYPE'
	}
*/

copiedError = copy(e);
/*
Throws error:
	internal/assert.js:14
		throw new ERR_INTERNAL_ASSERTION(message);
		^

	Error [ERR_INTERNAL_ASSERTION]: Code: ERR_INVALID_ARG_TYPE; The provided arguments length (1) does not match the required ones (3).
	This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
	Please open an issue with this stack trace at https://github.com/nodejs/node/issues

		at assert (internal/assert.js:14:11)
		at getMessage (internal/errors.js:347:5)
		at new NodeError (internal/errors.js:261:23)
		at copy (node_modules\utils-copy-error\lib\copy.js:29:8)
		at Object.<anonymous> (example.js:9:10)
		at Module._compile (internal/modules/cjs/loader.js:1256:30)
		at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
		at Module.load (internal/modules/cjs/loader.js:1105:32)
		at Function.Module._load (internal/modules/cjs/loader.js:967:14)
		at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
	  code: 'ERR_INTERNAL_ASSERTION'
	}
 */
```

**Comment by kgryte** [comment]
Thanks! Let me try and reproduce on my end, and I'll circle back.

**Comment by kgryte** [comment]
Okay. I investigated. At some point, Node.js moved away from vanilla V8 errors (`Error`, `TypeError`, etc) and created a custom error type `NodeError`. Unfortunately, I am not really able to make heads or tails of what the (internal) `NodeError` constructor expects as arguments (see [here](https://github.com/nodejs/node/blob/eeb6b473fd9f8399583fafe1807781dd1e760c5e/lib/internal/errors.js#L255)). Currently, this package assumes that the error to be copied is a vanilla error object, or at least, if a subclass, something that has the same signature.

Unfortunately, the internal `NodeError` objects do not have such a signature. And I am not sure how to go about providing such support.

If you have any ideas, LMK.

**Comment by thelaughingwolf** [comment]
Thanks for investigating! I'll look into it some myself.

**Comment by thelaughingwolf** [comment]
Oof, this was fun.

I can see the fundamental error is fired by an `assert` in `getMessage`. And the messages are preloaded by the [convenience method `E`](https://github.com/nodejs/node/blob/eeb6b473fd9f8399583fafe1807781dd1e760c5e/lib/internal/errors.js#L332). So when you call `error.constructor`, it is actually trying to create a new `NodeError` with code `ERR_INVALID_ARG_TYPE`, which was defined [here](https://github.com/nodejs/node/blob/eeb6b473fd9f8399583fafe1807781dd1e760c5e/lib/internal/errors.js#L980). *That's* the method that maps to `error.constructor`, and *that's* the method that needs three arguments. So Node thinks you're trying to register a method to warn about an incorrect parameter count, but then misusing the error constructor.

It's also clear from that long list that each predefined `NodeError` type expects its own list of arguments and types. It's definitely not feasible to try to replicate each code.

Perhaps, if `error instanceof NodeError` is true, you could copy the error some other way?

**Comment by kgryte** [comment]
Yeah, the above was my conclusion, as well.

Re: copy. I am not sure if there is a viable way forward on this one. As we really cannot copy the `NodeError` instance without invoking its constructor. At least, we would not be able to copy it exactly.

We could, possibly, check if a `NodeError` instance is one of the built-in error types (e.g., `TypeError`, `URIError`, etc), and, if so, copy the error info to a new built-in error instance. This would not be 1:1, and it depends on the use case, I suppose, but this could be a way forward.
